### ISSUE TITLE
Add i18n & translations support

### ISSUE THREAD

**Issue by ceolson01** [JoinColony/JoinColony.github.io#10]
## Description

Like the dApp, add in i18n / `react-intl` support.

The following resources may be of help:

- https://github.com/gatsbyjs/gatsby/issues/3853
- https://github.com/gatsbyjs/gatsby/issues/3830#issuecomment-362710469

## Todo

- [x] Install deps
- [x] Set up app-wide provider
- [x] `defineMessages` in all components
- [x] Determine how to denote alternate languages for docs
- [x] Update Gatsby transform plugins to utilize multiple locales for docs
- [x] Use Subdirectories with gTLD vs URL parameters for setting locale
- [x] Allow for translatable sections in docs
