### ISSUE TITLE
Website - Edits - R2

### ISSUE THREAD

**Issue by ceolson01** [JoinColony/JoinColony.github.io#108]
This issue tracks revisions.

**TODO**

General

- [x] Adjust all h1s to match H0 and H1 from web guide
- [x] Replace all `p`s with `Paragraph` component

Next steps for design

- [x] Main: replace code image
- [x] Use updated slider images
- [x] Lessen lightness of drop shadow in slider (for over blue portions)
- [x] Dropdown item hover - match [figma spec](https://www.figma.com/file/Kivlap6yvF5NQNJN1bUCYW/Main?node-id=3478%3A1974)

Product Platform Page

- [x] Investigate bleed issue (see: [this comment](https://github.com/JoinColony/JoinColony.github.io/pull/110#discussion_r312211762))
