### ISSUE TITLE
Dev Portal - Pre-Launch Checklist

### ISSUE THREAD

**Issue by ceolson01** [JoinColony/JoinColony.github.io#40]
The aim of this issue is to keep track of all items that need to be completed before launching the Developer Portal.

## TODO

- [x] Ensure `logoSmall` (this one will be the logomark) images are added and the project description in the docs configuration is up-to-date for each project.
  - [x] JoinColony/colonyStarter#79
  - [x] JoinColony/colonyNetwork#580
  - [x] JoinColony/colonyJS#379
  - [x] JoinColony/purser#217
  - [x] JoinColony/tailor#74
- [x] Algolia docsearch config includes all OSed projects. Our config can be found [here](https://github.com/algolia/docsearch-configs/blob/master/configs/colony.json).
- [x] Landing page complete
- [x] Docs template complete
- [x] Tutorials
  - [x] Template complete
  - [x] Sourcing plugin complete
- [x] Mobile styles
- [x] Remove `tutorials` temporarily
- [x] Move `/developers/` to `/`
- [x] Move `/docs/*/` to `/*/`
