### ISSUE TITLE
Dev Portal - Dashboard Pre-Launch Checklist

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/JoinColony.github.io#62]
### Dashboard Pre-Launch Checklist 

The following items need to be completed before launch:

#### Group 1
- [x] Update dashboard pages to latest designs
- [x] Add loading indicators to buttons and content
- [x] Implement updated designs for error messages
- [x] Resolve first round of issues raised in [Product QA](https://docs.google.com/spreadsheets/d/1IGQRDIew8e6jI5viaTcS2WtZQelSOZ_CUfNruhw-l8g/edit#gid=0)

#### Group 2
- [x] Update routes and links to use constants for all paths
  - https://github.com/JoinColony/JoinColony.github.io/pull/61#discussion_r291419316 
  - https://github.com/JoinColony/JoinColony.github.io/pull/61#discussion_r291419409
- [x] Add colonyJS documentation for registering ENS labels
- [x] Add dynamic query to show more contributions and issues
- [x] Update colonyJS `getReputation` and add to account page
- [x] Resolve second round of issues raised in [Product QA](https://docs.google.com/spreadsheets/d/1IGQRDIew8e6jI5viaTcS2WtZQelSOZ_CUfNruhw-l8g/edit#gid=0)

#### Group 3
- [x] Implement updated designs for contribute page
- [x] Add mobile styling for pages that do not require metamask
- [x] Polish off styling for dashboard and contribute page
  - https://github.com/JoinColony/JoinColony.github.io/pull/61#discussion_r291420194
- [x] Resolve third round of issues raised in [Product QA](https://docs.google.com/spreadsheets/d/1IGQRDIew8e6jI5viaTcS2WtZQelSOZ_CUfNruhw-l8g/edit#gid=0)

#### Group 4
- [x] Create token and colony on goerli and mainnet
- [x] Register ENS label for colonies on goerli and mainnet
